// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Article documents */
interface ArticleDocumentData {
    /**
     * Title field in *Article*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Title of the article
     * - **API ID Path**: article.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Publish Date field in *Article*
     *
     * - **Field Type**: Date
     * - **Placeholder**: Date the article was published
     * - **API ID Path**: article.publishDate
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    publishDate: prismicT.DateField;
    /**
     * Featured Image field in *Article*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: article.featuredImage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    featuredImage: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Article*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: article.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<ArticleDocumentDataSlicesSlice>;
}
/**
 * Slice for *Article → Slice Zone*
 *
 */
type ArticleDocumentDataSlicesSlice = ImageSlice | QuoteSlice | TextSlice | ContactFormSlice;
/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, "article", Lang>;
/** Content for articleList documents */
type ArticlelistDocumentData = Record<string, never>;
/**
 * articleList document from Prismic
 *
 * - **API ID**: `articlelist`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlelistDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ArticlelistDocumentData>, "articlelist", Lang>;
/** Content for Nuevo Destino documents */
interface DestinosDocumentData {
    /**
     * Title field in *Nuevo Destino*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: destinos.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *Nuevo Destino*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: destinos.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<DestinosDocumentDataSlicesSlice>;
}
/**
 * Slice for *Nuevo Destino → Slice Zone*
 *
 */
type DestinosDocumentDataSlicesSlice = HeroSectionSlice | ProductCardWithPriceSlice;
/**
 * Nuevo Destino document from Prismic
 *
 * - **API ID**: `destinos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DestinosDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DestinosDocumentData>, "destinos", Lang>;
/** Content for FAQ documents */
interface FaqDocumentData {
    /**
     * Slice Zone field in *FAQ*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<FaqDocumentDataSlicesSlice>;
}
/**
 * Slice for *FAQ → Slice Zone*
 *
 */
type FaqDocumentDataSlicesSlice = FaqSlice;
/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<FaqDocumentData>, "faq", Lang>;
/** Content for Navigation documents */
interface NavigationDocumentData {
    /**
     * Homepage Label field in *Navigation*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Label for the homepage link
     * - **API ID Path**: navigation.homepageLabel
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    homepageLabel: prismicT.TitleField;
    /**
     * Links field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.links[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    links: prismicT.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}
/**
 * Item in Navigation → Links
 *
 */
export interface NavigationDocumentDataLinksItem {
    /**
     * Label field in *Navigation → Links*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Optional - Label for the link
     * - **API ID Path**: navigation.links[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    label: prismicT.TitleField;
    /**
     * Link field in *Navigation → Links*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link for navigation item
     * - **API ID Path**: navigation.links[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Title for the page
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = ImageSlice | QuoteSlice | TextSlice | ContactFormSlice | ArticleListsSlice | BannerSlice | ProductCardSlice | ProductCardWithPriceSlice | ListaDestinosSlice | HeroSectionSlice | Banner2Slice | HeroSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Settings documents */
interface SettingsDocumentData {
    /**
     * Name field in *Settings*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Name of your blog (e.g. your name)
     * - **API ID Path**: settings.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.TitleField;
    /**
     * Description field in *Settings*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Short description of your blog
     * - **API ID Path**: settings.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Profile Picture field in *Settings*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.profilePicture
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profilePicture: prismicT.ImageField<never>;
    /**
     * Newsletter Description field in *Settings*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Text above the sign up form
     * - **API ID Path**: settings.newsletterDescription
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletterDescription: prismicT.RichTextField;
    /**
     * Newsletter Disclaimer field in *Settings*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Small text below sign up form
     * - **API ID Path**: settings.newsletterDisclaimer
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    newsletterDisclaimer: prismicT.RichTextField;
}
/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, "settings", Lang>;
export type AllDocumentTypes = ArticleDocument | ArticlelistDocument | DestinosDocument | FaqDocument | NavigationDocument | PageDocument | SettingsDocument;
/**
 * Default variation for ArticleLists Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ArticleLists`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleListsSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *ArticleLists*
 *
 */
type ArticleListsSliceVariation = ArticleListsSliceDefault;
/**
 * ArticleLists Shared Slice
 *
 * - **API ID**: `article_lists`
 * - **Description**: `ArticleLists`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArticleListsSlice = prismicT.SharedSlice<"article_lists", ArticleListsSliceVariation>;
/**
 * Primary content in Banner → Primary
 *
 */
interface BannerSliceDefaultPrimary {
    /**
     * header_image field in *Banner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.header_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    header_image: prismicT.ImageField<never>;
    /**
     * small_title field in *Banner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.small_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    small_title: prismicT.RichTextField;
    /**
     * title field in *Banner → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * button_label field in *Banner → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.button_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    button_label: prismicT.KeyTextField;
    /**
     * button_link field in *Banner → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.button_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    button_link: prismicT.LinkField;
    /**
     * image field in *Banner → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * color_de_fondo field in *Banner → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Color De Fondo
     * - **API ID Path**: banner.primary.color_de_fondo
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    color_de_fondo: prismicT.SelectField<"Blanco" | "Gris" | "Celeste" | "Morado" | "Amarillo" | "Naranja">;
    /**
     * opacidad_de_fondo field in *Banner → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: Opacidad Fondo 1 claro - 5 obscuro
     * - **API ID Path**: banner.primary.opacidad_de_fondo
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    opacidad_de_fondo: prismicT.SelectField<"1" | "2" | "3" | "4" | "5">;
    /**
     * color_small_title field in *Banner → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.color_small_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    color_small_title: prismicT.SelectField<"Blanco" | "Gris" | "Celeste" | "Morado" | "Amarillo" | "Naranja">;
    /**
     * op_color_small_title field in *Banner → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: Opacit Smalltext (1 claro - 5 obsc)
     * - **API ID Path**: banner.primary.op_color_small_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    op_color_small_title: prismicT.NumberField;
    /**
     * color_title field in *Banner → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.primary.color_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    color_title: prismicT.SelectField<"Blanco" | "Gris" | "Celeste" | "Morado" | "Amarillo" | "Naranja">;
    /**
     * op_color_title field in *Banner → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: 1 claro - 5 obscuro
     * - **API ID Path**: banner.primary.op_color_title
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    op_color_title: prismicT.NumberField;
}
/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<BannerSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Banner*
 *
 */
type BannerSliceVariation = BannerSliceDefault;
/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSlice = prismicT.SharedSlice<"banner", BannerSliceVariation>;
/**
 * Primary content in Banner2 → Primary
 *
 */
interface Banner2SliceDefaultPrimary {
    /**
     * title field in *Banner2 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner2.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Banner2 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner2.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * texto boton principal field in *Banner2 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner2.primary.principal_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    principal_text: prismicT.KeyTextField;
    /**
     * link boton principal field in *Banner2 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner2.primary.link_boton_principal
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_boton_principal: prismicT.LinkField;
    /**
     * texto boton secundario field in *Banner2 → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner2.primary.secondary_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    secondary_text: prismicT.KeyTextField;
    /**
     * link boton secundario field in *Banner2 → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: banner2.primary.link_boton_secundario
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_boton_secundario: prismicT.LinkField;
    /**
     * imagen field in *Banner2 → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner2.primary.imagen
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    imagen: prismicT.ImageField<never>;
}
/**
 * Default variation for Banner2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Banner2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Banner2SliceDefault = prismicT.SharedSliceVariation<"default", Simplify<Banner2SliceDefaultPrimary>, never>;
/**
 * Slice variation for *Banner2*
 *
 */
type Banner2SliceVariation = Banner2SliceDefault;
/**
 * Banner2 Shared Slice
 *
 * - **API ID**: `banner2`
 * - **Description**: `Banner2`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type Banner2Slice = prismicT.SharedSlice<"banner2", Banner2SliceVariation>;
/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ContactForm`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactFormSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *ContactForm*
 *
 */
type ContactFormSliceVariation = ContactFormSliceDefault;
/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: `ContactForm`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ContactFormSlice = prismicT.SharedSlice<"contact_form", ContactFormSliceVariation>;
/**
 * Primary content in Faq → Primary
 *
 */
interface FaqSliceDefaultPrimary {
    /**
     * title field in *Faq → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * description field in *Faq → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
}
/**
 * Item in Faq → Items
 *
 */
export interface FaqSliceDefaultItem {
    /**
     * pregunta field in *Faq → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.items[].pregunta
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    pregunta: prismicT.KeyTextField;
    /**
     * respuesta field in *Faq → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.items[].respuesta
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    respuesta: prismicT.KeyTextField;
}
/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FaqSliceDefaultPrimary>, Simplify<FaqSliceDefaultItem>>;
/**
 * Slice variation for *Faq*
 *
 */
type FaqSliceVariation = FaqSliceDefault;
/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSlice = prismicT.SharedSlice<"faq", FaqSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
    /**
     * imagen field in *Hero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero.primary.imagen
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    imagen: prismicT.ImageField<never>;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<"hero", HeroSliceVariation>;
/**
 * Primary content in HeroSection → Primary
 *
 */
interface HeroSectionSliceDefaultPrimary {
    /**
     * Titulo en negro field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.titulo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    titulo: prismicT.KeyTextField;
    /**
     * titulo en color principal field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.titulo_principal
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    titulo_principal: prismicT.KeyTextField;
    /**
     * parrafo field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.parrafo
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    parrafo: prismicT.KeyTextField;
    /**
     * texto boton azul field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.texto_boton_azul
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    texto_boton_azul: prismicT.KeyTextField;
    /**
     * texto boton blanco field in *HeroSection → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.texto_boton_blanco
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    texto_boton_blanco: prismicT.KeyTextField;
    /**
     * link boton azul field in *HeroSection → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.link_boton_azul
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_boton_azul: prismicT.LinkField;
    /**
     * link boton blanco field in *HeroSection → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.link_boton_blanco
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_boton_blanco: prismicT.LinkField;
    /**
     * imagen de fondo field in *HeroSection → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: hero_section.primary.imagen_de_fondo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    imagen_de_fondo: prismicT.ImageField<never>;
}
/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HeroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HeroSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HeroSection*
 *
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;
/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: `HeroSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSectionSlice = prismicT.SharedSlice<"hero_section", HeroSectionSliceVariation>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceDefaultPrimary {
    /**
     * Image field in *Image → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Caption field in *Image → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Optional - Caption under the image
     * - **API ID Path**: image.primary.caption
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption: prismicT.RichTextField;
}
/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageSliceDefaultPrimary>, never>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceWidePrimary {
    /**
     * Image field in *Image → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Caption field in *Image → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Optional - Caption under the image
     * - **API ID Path**: image.primary.caption
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    caption: prismicT.RichTextField;
}
/**
 * Wide variation for Image Slice
 *
 * - **API ID**: `wide`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceWide = prismicT.SharedSliceVariation<"wide", Simplify<ImageSliceWidePrimary>, never>;
/**
 * Slice variation for *Image*
 *
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceWide;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSlice = prismicT.SharedSlice<"image", ImageSliceVariation>;
/**
 * Primary content in ListaDestinos → Primary
 *
 */
interface ListaDestinosSliceDefaultPrimary {
    /**
     * titulo de la seccion field in *ListaDestinos → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: lista_destinos.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * subtitulo o descripcion field in *ListaDestinos → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: lista_destinos.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Color de Fondo field in *ListaDestinos → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: lista_destinos.primary.color_de_fondo
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    color_de_fondo: prismicT.SelectField<"Blanco" | "Gris" | "Celeste" | "Naranja" | "Morado" | "Amarillo">;
    /**
     * Opacidad de fondo field in *ListaDestinos → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: 1 claro - 5 obscuro
     * - **API ID Path**: lista_destinos.primary.opacidad_de_fondo
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    opacidad_de_fondo: prismicT.NumberField;
    /**
     * color de texto field in *ListaDestinos → Primary*
     *
     * - **Field Type**: Select
     * - **Placeholder**: *None*
     * - **API ID Path**: lista_destinos.primary.color_de_texto
     * - **Documentation**: https://prismic.io/docs/core-concepts/select
     *
     */
    color_de_texto: prismicT.SelectField<"Blanco" | "Gris" | "Celeste" | "Naranja" | "Morado" | "Amarillo">;
    /**
     * opacidad color de texto field in *ListaDestinos → Primary*
     *
     * - **Field Type**: Number
     * - **Placeholder**: 1 claro, 5 obscuro
     * - **API ID Path**: lista_destinos.primary.opacidad_color_de_texto
     * - **Documentation**: https://prismic.io/docs/core-concepts/number
     *
     */
    opacidad_color_de_texto: prismicT.NumberField;
}
/**
 * Item in ListaDestinos → Items
 *
 */
export interface ListaDestinosSliceDefaultItem {
    /**
     * texto pequeño field in *ListaDestinos → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lista_destinos.items[].smalltext
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    smalltext: prismicT.KeyTextField;
    /**
     * Texto principal field in *ListaDestinos → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: lista_destinos.items[].principal_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    principal_text: prismicT.KeyTextField;
    /**
     * imagenFondo field in *ListaDestinos → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: lista_destinos.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * link de pagina o enlace al dar click field in *ListaDestinos → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: lista_destinos.items[].link_route
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link_route: prismicT.LinkField;
}
/**
 * Default variation for ListaDestinos Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ListaDestinos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ListaDestinosSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ListaDestinosSliceDefaultPrimary>, Simplify<ListaDestinosSliceDefaultItem>>;
/**
 * Slice variation for *ListaDestinos*
 *
 */
type ListaDestinosSliceVariation = ListaDestinosSliceDefault;
/**
 * ListaDestinos Shared Slice
 *
 * - **API ID**: `lista_destinos`
 * - **Description**: `ListaDestinos`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ListaDestinosSlice = prismicT.SharedSlice<"lista_destinos", ListaDestinosSliceVariation>;
/**
 * Primary content in ListaDeToursConPrecio → Primary
 *
 */
interface ProductCardWithPriceSliceDefaultPrimary {
    /**
     * title field in *ListaDeToursConPrecio → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: *None*
     * - **API ID Path**: product_card_with_price.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * description field in *ListaDeToursConPrecio → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: product_card_with_price.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in ListaDeToursConPrecio → Items
 *
 */
export interface ProductCardWithPriceSliceDefaultItem {
    /**
     * Texto Principal field in *ListaDeToursConPrecio → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: product_card_with_price.items[].principal_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    principal_text: prismicT.KeyTextField;
    /**
     * desde valor field in *ListaDeToursConPrecio → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: product_card_with_price.items[].desde
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    desde: prismicT.KeyTextField;
    /**
     * link field in *ListaDeToursConPrecio → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: product_card_with_price.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * imagen field in *ListaDeToursConPrecio → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: product_card_with_price.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for ListaDeToursConPrecio Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProductCardWithPrice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductCardWithPriceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProductCardWithPriceSliceDefaultPrimary>, Simplify<ProductCardWithPriceSliceDefaultItem>>;
/**
 * Slice variation for *ListaDeToursConPrecio*
 *
 */
type ProductCardWithPriceSliceVariation = ProductCardWithPriceSliceDefault;
/**
 * ListaDeToursConPrecio Shared Slice
 *
 * - **API ID**: `product_card_with_price`
 * - **Description**: `ProductCardWithPrice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductCardWithPriceSlice = prismicT.SharedSlice<"product_card_with_price", ProductCardWithPriceSliceVariation>;
/**
 * Primary content in ProductCard → Primary
 *
 */
interface ProductCardSliceDefaultPrimary {
    /**
     * Title field in *ProductCard → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: product_card.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ProductCard → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: product_card.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for ProductCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ProductCard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductCardSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ProductCardSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ProductCard*
 *
 */
type ProductCardSliceVariation = ProductCardSliceDefault;
/**
 * ProductCard Shared Slice
 *
 * - **API ID**: `product_card`
 * - **Description**: `ProductCard`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductCardSlice = prismicT.SharedSlice<"product_card", ProductCardSliceVariation>;
/**
 * Primary content in Quote → Primary
 *
 */
interface QuoteSliceDefaultPrimary {
    /**
     * Quote field in *Quote → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Quote without quotation marks
     * - **API ID Path**: quote.primary.quote
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    quote: prismicT.TitleField;
    /**
     * Source field in *Quote → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: Source of the quote
     * - **API ID Path**: quote.primary.source
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    source: prismicT.KeyTextField;
}
/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Quote`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuoteSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<QuoteSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Quote*
 *
 */
type QuoteSliceVariation = QuoteSliceDefault;
/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: `Quote`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuoteSlice = prismicT.SharedSlice<"quote", QuoteSliceVariation>;
/**
 * Primary content in Text → Primary
 *
 */
interface TextSliceDefaultPrimary {
    /**
     * Text field in *Text → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Text with rich formatting
     * - **API ID Path**: text.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Text*
 *
 */
type TextSliceVariation = TextSliceDefault;
/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSlice = prismicT.SharedSlice<"text", TextSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ArticleDocumentData, ArticleDocumentDataSlicesSlice, ArticleDocument, ArticlelistDocumentData, ArticlelistDocument, DestinosDocumentData, DestinosDocumentDataSlicesSlice, DestinosDocument, FaqDocumentData, FaqDocumentDataSlicesSlice, FaqDocument, NavigationDocumentData, NavigationDocumentDataLinksItem, NavigationDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, SettingsDocumentData, SettingsDocument, AllDocumentTypes, ArticleListsSliceDefault, ArticleListsSliceVariation, ArticleListsSlice, BannerSliceDefaultPrimary, BannerSliceDefault, BannerSliceVariation, BannerSlice, Banner2SliceDefaultPrimary, Banner2SliceDefault, Banner2SliceVariation, Banner2Slice, ContactFormSliceDefault, ContactFormSliceVariation, ContactFormSlice, FaqSliceDefaultPrimary, FaqSliceDefaultItem, FaqSliceDefault, FaqSliceVariation, FaqSlice, HeroSliceDefaultPrimary, HeroSliceDefault, HeroSliceVariation, HeroSlice, HeroSectionSliceDefaultPrimary, HeroSectionSliceDefault, HeroSectionSliceVariation, HeroSectionSlice, ImageSliceDefaultPrimary, ImageSliceDefault, ImageSliceWidePrimary, ImageSliceWide, ImageSliceVariation, ImageSlice, ListaDestinosSliceDefaultPrimary, ListaDestinosSliceDefaultItem, ListaDestinosSliceDefault, ListaDestinosSliceVariation, ListaDestinosSlice, ProductCardWithPriceSliceDefaultPrimary, ProductCardWithPriceSliceDefaultItem, ProductCardWithPriceSliceDefault, ProductCardWithPriceSliceVariation, ProductCardWithPriceSlice, ProductCardSliceDefaultPrimary, ProductCardSliceDefault, ProductCardSliceVariation, ProductCardSlice, QuoteSliceDefaultPrimary, QuoteSliceDefault, QuoteSliceVariation, QuoteSlice, TextSliceDefaultPrimary, TextSliceDefault, TextSliceVariation, TextSlice };
    }
}
