// Code generated by Slice Machine. DO NOT EDIT.

import ArticleLists from './ArticleLists';
import Banner from './Banner';
import Banner2 from './Banner2';
import ContactForm from './ContactForm';
import Faq from './Faq';
import Hero from './Hero';
import HeroSection from './HeroSection';
import Image from './Image';
import ListaDestinos from './ListaDestinos';
import ListaDeToursConPrecio from './ListaDeToursConPrecio';
import ProductCard from './ProductCard';
import Quote from './Quote';
import Text from './Text';

export {
	ArticleLists,
	Banner,
	Banner2,
	ContactForm,
	Faq,
	Hero,
	HeroSection,
	Image,
	ListaDestinos,
	ListaDeToursConPrecio,
	ProductCard,
	Quote,
	Text,
};

export const components = {
	article_lists: ArticleLists,
	banner: Banner,
	banner2: Banner2,
	contact_form: ContactForm,
	faq: Faq,
	hero: Hero,
	hero_section: HeroSection,
	image: Image,
	lista_destinos: ListaDestinos,
	product_card_with_price: ListaDeToursConPrecio,
	product_card: ProductCard,
	quote: Quote,
	text: Text,
};
