// Code generated by Slice Machine. DO NOT EDIT.

import ArticleLists from './ArticleLists';
import Banner from './Banner';
import ContactForm from './ContactForm';
import HeroSection from './HeroSection';
import Image from './Image';
import ListaDestinos from './ListaDestinos';
import ProductCard from './ProductCard';
import ProductCardWithPrice from './ProductCardWithPrice';
import Quote from './Quote';
import Text from './Text';

export {
	ArticleLists,
	Banner,
	ContactForm,
	HeroSection,
	Image,
	ListaDestinos,
	ProductCard,
	ProductCardWithPrice,
	Quote,
	Text,
};

export const components = {
	article_lists: ArticleLists,
	banner: Banner,
	contact_form: ContactForm,
	hero_section: HeroSection,
	image: Image,
	lista_destinos: ListaDestinos,
	product_card: ProductCard,
	product_card_with_price: ProductCardWithPrice,
	quote: Quote,
	text: Text,
};
