// Code generated by Slice Machine. DO NOT EDIT.

import ArticleLists from './ArticleLists';
import Banner from './Banner';
import ContactForm from './ContactForm';
import Image from './Image';
import ProductCard from './ProductCard';
import Quote from './Quote';
import Text from './Text';

export {
	ArticleLists,
	Banner,
	ContactForm,
	Image,
	ProductCard,
	Quote,
	Text,
};

export const components = {
	article_lists: ArticleLists,
	banner: Banner,
	contact_form: ContactForm,
	image: Image,
	product_card: ProductCard,
	quote: Quote,
	text: Text,
};
